### ISSUE TITLE
CocoaPods specs repo missing the latest (few latest) versions

### ISSUE THREAD

**Issue by alexmx** [marmelroy/PhoneNumberKit#530]
Latest available version of `PhoneNumberKit` in the CocoaPods specs repo is [`3.3.4`](https://cocoapods.org/pods/PhoneNumberKit)

Latest `PhoneNumberKit` version is [`3.4.1`](https://github.com/marmelroy/PhoneNumberKit/releases/tag/3.4.1) and it is missing from the specs repo. 

I see that the [`Podspec`](https://github.com/marmelroy/PhoneNumberKit/blob/master/PhoneNumberKit.podspec) file is updated with the correct version in master so seems like somebody needs to push it to the CocoaPods repo. 

Could this be done please?

**Comment by bguidolim** [comment]
Sorry, but I don't have rights to to so. The only one who can do it is @marmelroy

**Comment by petermolnar-dev** [comment]
@alexmx As a temporary workaround you can update your Podfile to have the git source for this repo, so it will be kept updated:
`pod 'PhoneNumberKit', :git => 'https://github.com/marmelroy/PhoneNumberKit'`

**Comment by gerry-wood-sumup** [comment]
Really need to have this updated as the current podspec if used on a `M11 machine will cause a crash in the `PartialFormatter`

We temporarily  pointed our podfile to the `:git => 'https://github.com/marmelroy/PhoneNumberKit', :tag => '3.4.1'`, but I would ask that the podspec be updated on the main cocoapods CDN if possible.

**Comment by petermolnar-dev** [comment]
@gerry-wood-sumup : For us it was working well with my suggestion. Indeed, without the CocoaPods CDN it was slowly resolved in our CI/CD. As a solution we moved (only this package for now) under SwiftPM. 

Actually at the moment we are using SwiftPM and CocoaPods together in that particular project, with the intention of migrating all dependencies to SwiftPM. If you don't have other constraints you can give a try on that configuration as well.

**Comment by kubatruhlar** [comment]
Hi @marmelroy, this needs to be reopened as the latest versions are still not available.
