### ISSUE TITLE
Phone number parsing is not working on iOS 17

### ISSUE THREAD

**Issue by WedgeSparda** [marmelroy/PhoneNumberKit#659]
### New Issue Checklist

- [X] Updated PhoneNumberKit to the latest version / Specified the podspec directly from the repo
- [X] Phone number formatted correctly on [JavaScript version](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html)
- [X] I searched for [existing GitHub issues](https://github.com/marmelroy/PhoneNumberKit)

### Steps to reproduce

- Download [this test project](https://github.com/WedgeSparda/PhoneNumberKitTest).
- Open it with XCode 14/iOS 16.4
- Test phone number (+34 666666666)  is parsed correctly
- Open the same project with XCode 15 (Beta)/iOS 17
- Test phone number (+34 666666666) is not parsed correctly, returning `invalidNumber` error

##### Expected result

Phone number parsing should work on iOS 17 as is working right now on iOS 16

##### Actual result

Phone number parsing is not working and returning `invalidNumber` error

### Environment

Library added via SPM on XCode 14.

**Comment by bguidolim** [comment]
This issue happens when the library tries to get the region from the device's SIM card with the following code:
```swift
let countryCode = CNContactsUserDefaults.shared().countryCode.uppercased()
```
On iOS 17 Beta, it returns "001" on simulators (maybe on physical devices too) instead of the ISO country code.

Since it's just the first beta available, I would wait until the release candidate before changing something on PNK.

**Comment by bourvill** [comment]
Hello, do you have the same issue with iOS 16.5 ?

I can't find a way to install the 16.5 simulator. 
But many of our users report us a problem with the validation of the phone number, and it seems to be related to the version of ios 16.5

**Comment by WedgeSparda** [comment]
@bourvill Tested on device with iOS 16.5 and worked correctly

**Comment by lveecode** [comment]
@bourvill @WedgeSparda  Reproduces for me on iOS 16.5 (real device, eSim, carrier is Vodafone Ukraine). 
The region/carrier country code `carrier?.isoCountryCode` in `defaultRegionCode()` is `"--"` instead of the country code. The fallback to "US" doesn't work since `"--"` is still a value. 

<img width="731" alt="Screenshot 2023-06-22 at 13 22 18" src="https://github.com/marmelroy/PhoneNumberKit/assets/15900746/da4fe9eb-382f-4abe-9a1a-5ad90dcbc4eb">

**Comment by bguidolim** [comment]
This is not the same issue. You’re using an old version of PhoneNumberKit.

Please, keep in mind that if you’re using Cocoapods as dependency manager, you must specify the git parameter on your Podfile as described on README.

**Comment by bguidolim** [comment]
@WedgeSparda Seems it was fixed on beta 2.

**Comment by WedgeSparda** [comment]
@bguidolim It is, indeed. Just tested it and is returning a valid parsed phone. Thanks.

**Comment by keremerkan** [comment]
This problem is still present on Xcode 15 and iOS 17 simulator with PhoneNumberKit 3.7.2 installed via SPM. It does not happen on the device.
